my_weather_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: "{{ env_var('DBT_POSTGRES_USER')}}"
      password: "{{ env_var('DBT_POSTGRES_PASSWORD')}}"
      port: 5432
      dbname: weather_values
      schema: weather

# add this to the readme later on 
# $env:DBT_POSTGRES_USER = "postgres"
# $env:DBT_POSTGRES_PASSWORD = "dbt_pass123"